using System;
using System.Collections.Generic;
using UnityEngine;

namespace Halcyon
{
    /// <summary>Prefab registry generated by the editor pipeline (Assets/GTA/Resources/GameDatabase.asset).</summary>
    public class GameDatabase : ScriptableObject
    {
        [Serializable] public class Entry { public string id; public GameObject prefab; }
        public List<Entry> entries = new List<Entry>();
        public Texture2D mapTexture;
        public Material waterMaterial, skyMaterial, fxAlpha, fxAdd, decal, line, uiMaterial;
        public Material[] paintFinishes;
        public Material[] nightMaterials;

        Dictionary<string, GameObject> map;
        static GameDatabase inst;

        public static GameDatabase I
        {
            get
            {
                if (inst == null) inst = Resources.Load<GameDatabase>("GameDatabase");
                return inst;
            }
        }

        public GameObject Get(string id)
        {
            if (map == null)
            {
                map = new Dictionary<string, GameObject>();
                foreach (var e in entries) if (e.prefab != null) map[e.id] = e.prefab;
            }
            map.TryGetValue(id, out var p);
            return p;
        }

        public bool Has(string id) => Get(id) != null;
    }
}
